name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required Android components
        run: |
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.1"
          sdkmanager "platform-tools"

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BossTimer-APK
          path: app/build/outputs/apk/debug/app-debug.apk