name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，确保所有文件都被检出

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Verify project structure
        run: |
          echo "=== Project Structure ==="
          ls -la
          echo "=== Gradle files ==="
          find . -name "gradlew" -o -name "build.gradle" -o -name "gradle-wrapper.properties" | head -20

      - name: Build with Gradle
        run: |
          # 如果gradlew存在，使用它；否则使用全局gradle
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew assembleDebug --stacktrace
          else
            echo "gradlew not found, using global gradle"
            gradle assembleDebug --stacktrace
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BossTimer-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error